(() => {
  const API = (window.ARJUN_ADMIN_CONFIG?.apiBase || "/api").replace(/\/$/, "");
  const $ = s => document.querySelector(s);
  let token = sessionStorage.getItem("arjun_preview_token");
  let user = JSON.parse(sessionStorage.getItem("arjun_preview_user") || "null");
  let nodes = [], users = [], requests = [], selected = null, panel = "hierarchy";
  const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  async function request(path, options={}) {
    const r = await fetch(API + path, {headers:{"Content-Type":"application/json", ...(token?{Authorization:`Bearer ${token}`}:{})}, ...options});
    const data = await r.json().catch(()=>({detail:"The server returned an invalid response."}));
    if (!r.ok) throw new Error(data.detail || "Request failed");
    return data;
  }
  function setNotice(message, bad=false){ const n=$("#notice"); n.textContent=message; n.classList.toggle("bad",bad); }
  function children(id){ return nodes.filter(n=>(n.parent_project_id||null)===(id||null)); }
  function tree(parent=null,level=0){ return children(parent).map(n=>`<div class="node" style="--level:${level}"><button data-id="${esc(n.project_id)}" class="node-button ${selected===n.project_id?"selected":""}"><span>${n.node_type==="project_site"?"PS":"AD"}</span><div><b>${esc(n.name)}</b><small>${esc(n.administrator_role||"Role not set")} Â· ${esc(n.administrator_name||"Unassigned")}</small></div><em>#${esc(n.node_number||n.project_id)}</em></button>${tree(n.project_id,level+1)}</div>`).join(""); }
  function render(){ $("#tree").innerHTML=nodes.length?tree():"<p class='empty'>No active nodes are available to this account.</p>"; document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{selected=b.dataset.id; render(); detail();}); detail(); }
  function detail(){ const n=nodes.find(x=>x.project_id===selected); $("#detail").innerHTML=n?`<h2>${esc(n.name)}</h2><dl><dt>Role</dt><dd>${esc(n.administrator_role)}</dd><dt>Administrator</dt><dd>${esc(n.administrator_name||"Not assigned")}</dd><dt>Place</dt><dd>${esc(n.place||"Not set")}</dd><dt>Type</dt><dd>${n.node_type==="project_site"?"Project site":"Administrative unit"}</dd><dt>Workflow</dt><dd>${esc(n.project_type||"â€”")}</dd><dt>Direct children</dt><dd>${children(n.project_id).length}</dd></dl>`:"Select a node from the hierarchy."; }
  async function load(){ const d=await request("/admin/bootstrap"); nodes=d.nodes||[]; users=d.users||[]; requests=d.requests||[]; if(selected && !nodes.some(n=>n.project_id===selected)) selected=null; render(); setNotice(`Connected. ${nodes.length} nodes, ${users.length} users, ${requests.length} requests loaded from the preview database.`); }
  async function start(){ $("#adminApp").hidden=false; $("#who").textContent=`Signed in as ${user.name||user.email}`; try{await load();}catch(e){setNotice(e.message,true);} }
  function openDialog(){ const p=$("#parent"); p.innerHTML=`<option value="">No parent â€” top-level organisation</option>${nodes.map(n=>`<option value="${esc(n.project_id)}">${esc(n.name)} (#${esc(n.node_number||n.project_id)})</option>`).join("")}`; p.value=selected||""; $("#nodeError").textContent=""; $("#nodeDialog").showModal(); }
  async function create(e){e.preventDefault();const f=new FormData(e.currentTarget);const payload={name:f.get("name"),administrator_role:f.get("administrator_role"),place:f.get("place")||null,parent_project_id:f.get("parent_project_id")||null,node_type:f.get("node_type"),project_type:f.get("project_type"),can_subdivide:f.get("can_subdivide")==="on"}; try{const d=await request("/admin/nodes",{method:"POST",body:JSON.stringify(payload)}); selected=d.project_id; $("#nodeDialog").close(); e.currentTarget.reset(); await load(); setNotice(`Saved ${d.name||payload.name} to the preview database.`);}catch(err){$("#nodeError").textContent=err.message;}}
  function showPanel(name){panel=name; document.querySelectorAll("[data-panel]").forEach(b=>b.classList.toggle("active",b.dataset.panel===name)); const hierarchy=name==="hierarchy"; $("#hierarchyPanel").hidden=!hierarchy; $("#dataPanel").hidden=hierarchy; $("#newNode").hidden=!hierarchy; if(hierarchy){$("#panelTitle").textContent="My hierarchy"; render(); return;} const title={users:"Registered users",approvals:"Approvals",sites:"Project sites"}[name]; $("#panelTitle").textContent=title; $("#panelIntro").textContent="Live records from the preview database."; const rows=name==="users"?users.map(u=>`<tr><td>${esc(u.name||"â€”")}</td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${esc(u.project_id||"Unassigned")}</td></tr>`):name==="approvals"?requests.map(r=>`<tr><td>${esc(r.request_type)}</td><td>${esc(r.status)}</td><td>${esc(r.requested_at)}</td><td>${esc(r.parent_project_id||"â€”")}</td></tr>`):nodes.filter(n=>n.node_type==="project_site").map(n=>`<tr><td>${esc(n.name)}</td><td>${esc(n.project_type)}</td><td>${esc(n.place||"â€”")}</td><td>${esc(n.administrator_name||"Unassigned")}</td></tr>`); const heads=name==="users"?"Name,Email,Role,Assigned node":name==="approvals"?"Request,Status,Requested,Parent":"Project site,Workflow,Place,Administrator"; $("#dataPanel").innerHTML=`<h2>${title}</h2><table><thead><tr>${heads.split(",").map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.join(""):`<tr><td colspan="4">No records found.</td></tr>`}</tbody></table>`; }
  document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>showPanel(b.dataset.panel)); $("#signOut").onclick=()=>{sessionStorage.clear();location.href="index.html";}; $("#newNode").onclick=openDialog; $("#cancelDialog").onclick=()=>$("#nodeDialog").close(); $("#nodeForm").addEventListener("submit",create); if(token&&user) start(); else location.replace("index.html");
})();

